name: '${project.name}'
main: wgextender.WGExtender
api-version: '1.20'
version: '${project.version}'
author: _Shevchik_
depend: [WorldGuard, WorldEdit, Vault]
folia-supported: true
commands:
  wgextender:
    aliases: [wgex]
