name: '${project.name}'
main: wgextender.WGExtender
api-version: '1.13'
version: '${project.version}'
author: _Shevchik_
depend: [WorldGuard, WorldEdit, Vault]
commands:
  wgextender:
    aliases: [wgex]
